import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="max-w-7xl w-full  px-4 mx-auto py-10">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
